# THIS FILE SHOULD NOT BE EDITED
ios:
    socket_url:
        production: ssl://gateway.push.apple.com:2195
        development: ssl://gateway.sandbox.push.apple.com:2195
    credentials:
        - device_token
        - certificate_path
        - certificate_phrase
        - dev
ios_jwt:
    socket_url:
        production: api.push.apple.com
        development: api.development.push.apple.com
    credentials:
        - device_token
        - app_bundle_id
        - jwt
        - dev
android:
    socket_url:
        production: https://fcm.googleapis.com/fcm/send
        developemnt: %production%
    credentials:
        - device_token
        - google_api_key